# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='static/assets/img/post.jpg', upload_to='static/uploads', verbose_name='img'),
        ),
    ]
