# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='app/static/assets/img/post.jpg', upload_to='app/static/uploads', verbose_name='img'),
        ),
    ]
