# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160417_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='post.jpg', upload_to=b'', verbose_name='img'),
        ),
    ]
