# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160417_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='post.jpg', upload_to='media', verbose_name='img'),
        ),
    ]
